# Generated by Django 4.1.7 on 2024-06-27 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('couleur', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_debut_tache', models.DateTimeField(blank=True, null=True)),
                ('date_fin_tache', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_taches', to=settings.AUTH_USER_MODEL)),
                ('initiateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_taches', to=settings.AUTH_USER_MODEL)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statut', to='taches.statut')),
            ],
        ),
    ]
