# Generated by Django 4.1.7 on 2024-06-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('coouleur', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_debut_tache', models.DateTimeField(auto_now_add=True)),
                ('date_fin_tache', models.DateTimeField(auto_now_add=True)),
                ('executeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_taches', to='account.user')),
                ('initiateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_taches', to='account.user')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statut', to='taches.statut')),
            ],
        ),
    ]
