# Generated by Django 4.1.7 on 2024-06-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='quota',
            field=models.IntegerField(default=0),
        ),
    ]
