# Generated by Django 4.1.7 on 2024-06-20 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demande', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedemande',
            name='profils_optionnels',
            field=models.ManyToManyField(blank=True, related_name='types_demandes_optionnels', to='users.profil'),
        ),
        migrations.AddField(
            model_name='typedemande',
            name='profils_requis',
            field=models.ManyToManyField(blank=True, related_name='types_demandes_requis', to='users.profil'),
        ),
        migrations.AddField(
            model_name='demandevalidation',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='demande.demande'),
        ),
        migrations.AddField(
            model_name='demandevalidation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='initiateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='type_demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='demande.typedemande'),
        ),
        migrations.AddField(
            model_name='demande',
            name='validateurs',
            field=models.ManyToManyField(related_name='demandes_a_valider', through='demande.DemandeValidation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='demande.demande'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
