# Generated by Django 4.1.7 on 2024-06-04 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demande', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandevalidation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='initiateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='type_demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='demande.typedemande'),
        ),
        migrations.AddField(
            model_name='demande',
            name='validateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_demandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
