# Generated by Django 4.1.7 on 2024-06-27 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demande', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='validateurs',
        ),
        migrations.RemoveField(
            model_name='typedemande',
            name='profils_optionnels',
        ),
        migrations.RemoveField(
            model_name='typedemande',
            name='profils_requis',
        ),
        migrations.AddField(
            model_name='typedemande',
            name='validateurs_optionnels',
            field=models.ManyToManyField(blank=True, related_name='types_demandes_optionnels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typedemande',
            name='validateurs_requis',
            field=models.ManyToManyField(blank=True, related_name='types_demandes_requis', to=settings.AUTH_USER_MODEL),
        ),
    ]
